@startuml entity
entity entity {
  ユーザーID: user_id
  ユーザー名: user_name
  商品ID: product_id
  商品名: product_name
  価格: price
  カテゴリーID: category_id
  カテゴリー名: category_name
  購入日: purchase_day
  購入個数: purchase_count
}
@enduml

'エンティティを定義できる
'ユーザー1のマイページ
'○購入履歴
'・購入商品1（4/14購入）
'【商品】iPhone 13
'【カテゴリー】スマートフォン
'【値段】100,000円
'・購入商品2（4/17購入）
'【商品】キリン一番搾り生ビール10本
'【カテゴリー】ビール
'【値段】2,000円
'ここで表示されている情報がサイトで必要となる全ての種類データであるとします（ユーザーや商品は他にも存在しています）。
'このサイトの、データとして保存すべきエンティティを全て箇条書きで列挙してください。


